/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import core.MyProcessControl;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.AbstractListModel;
import javax.swing.ListModel;
import javax.swing.Timer;

/**
 *
 * @author hrmthw
 */
public class MainFrame extends javax.swing.JFrame {

    private MyProcessControl pcb;
 //   private Vector<String> processList;
    
    private final int DELAY=1000;
    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
        pcb=new MyProcessControl();
        initComponents();
        
        //init
//        processList=new Vector<String>();
        
        new Timer(DELAY,new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                pcb.step();
                update();
            }
        }).start();
     }

    public void update(){
        text_output.setText(pcb.output.toString());
        text_console.setText(pcb.action.toString());
        int tmpI=jList.getSelectedIndex();
        pcb.updateModel();
        jList.setSelectedIndex(tmpI);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        button_new = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        button_kill = new javax.swing.JButton();
        button_block = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_console = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        text_output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(450);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel4.setText(" pid     |        process name        |   user          |   status");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel4, java.awt.BorderLayout.CENTER);

        jLabel5.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jLabel5.setText("Process");
        jPanel6.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jTextField1.setColumns(15);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);

        button_new.setText("New");
        button_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_newActionPerformed(evt);
            }
        });
        jPanel2.add(button_new);
        jPanel2.add(jSeparator1);

        button_kill.setText("Kill");
        button_kill.setEnabled(false);
        button_kill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_killActionPerformed(evt);
            }
        });
        jPanel2.add(button_kill);

        button_block.setText("Block/Unblock");
        button_block.setEnabled(false);
        button_block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_blockActionPerformed(evt);
            }
        });
        jPanel2.add(button_block);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jList.setModel(pcb.getModel());
        jList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListValueChanged(evt);
                jListValueChanged1(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel3.setAutoscrolls(true);
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jLabel2.setText("Action");
        jPanel4.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        text_console.setEditable(false);
        text_console.setBackground(new java.awt.Color(1, 1, 1));
        text_console.setColumns(15);
        text_console.setForeground(new java.awt.Color(254, 254, 254));
        text_console.setRows(5);
        text_console.setMargin(new java.awt.Insets(0, 0, 10, 0));
        jScrollPane2.setViewportView(text_console);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane2.setTopComponent(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jLabel3.setText("Output");
        jPanel5.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        text_output.setEditable(false);
        text_output.setBackground(new java.awt.Color(1, 1, 1));
        text_output.setColumns(15);
        text_output.setForeground(new java.awt.Color(254, 254, 254));
        text_output.setRows(5);
        text_output.setMargin(new java.awt.Insets(0, 0, 10, 0));
        jScrollPane3.setViewportView(text_output);

        jPanel5.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jSplitPane2.setRightComponent(jPanel5);

        jPanel3.add(jSplitPane2);

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListValueChanged
        button_kill.setEnabled(true);
    }//GEN-LAST:event_jListValueChanged

    private void jListValueChanged1(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListValueChanged1
        button_block.setEnabled(true);
    }//GEN-LAST:event_jListValueChanged1

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void button_blockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_blockActionPerformed
        if (jList.isSelectionEmpty()) {
            return;
        }
        pcb.block(Integer.parseInt(((String)jList.getSelectedValue()).substring(0, 5).replace(" ","")));
        
    }//GEN-LAST:event_button_blockActionPerformed

    private void button_killActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_killActionPerformed
        if (jList.isSelectionEmpty()) {
            return;
        }        
        pcb.kill(Integer.parseInt(((String)jList.getSelectedValue()).substring(0, 5).replace(" ","")));
    }//GEN-LAST:event_button_killActionPerformed

    private void button_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_newActionPerformed
        if (jTextField1.getText().equals("")) {
            return;
        }
        pcb.loadProgram(jTextField1.getText(), "user");
        jTextField1.setText("");
    }//GEN-LAST:event_button_newActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_block;
    private javax.swing.JButton button_kill;
    private javax.swing.JButton button_new;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    javax.swing.JList jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea text_console;
    private javax.swing.JTextArea text_output;
    // End of variables declaration//GEN-END:variables
}
